[TH2-1473] Action 'ExecuteJsOnElement' added
th2-net/remotehand pull request #13
Opened 2021-02-11 14:18 UTC by danielsamatov

2021-02-11 18:08 UTC, Vladimir-Panarin-Exactpro requested changes

2021-02-11 18:08 UTC, Vladimir-Panarin-Exactpro commented on src/main/java/com/exactprosystems/remotehand/web/actions/ExecuteJsOnElement.java
> +/******************************************************************************
It is open source project. replace the copyright.

2021-02-12 07:59 UTC, Vladimir-Panarin-Exactpro requested changes
Copyright in WebJsUtils should also be fixed.

2021-02-12 11:53 UTC, Vladimir-Panarin-Exactpro reviewed
@battlemaster Please take a look.

2021-02-12 19:18 UTC, battlemaster reviewed
Also update version in gradle.properties.

2021-02-12 19:18 UTC, battlemaster commented on src/main/java/com/exactprosystems/remotehand/web/actions/ExecuteJS.java
>  		return null;
NPE alert. This value passes into RemoteWebDriver.executeScript, where is not expected null values as varargs. Use new Object[0]

2021-02-12 19:18 UTC, battlemaster commented on src/main/java/com/exactprosystems/remotehand/web/actions/ExecuteJsOnElement.java
> +		return params.get(JS_COMMANDS).replace(ELEMENT_PARAM, ARGUMENT);
Check params.get(JS_COMMANDS) is empty or null

2021-02-12 19:18 UTC, battlemaster commented on src/main/java/com/exactprosystems/remotehand/web/actions/ExecuteJS.java
> +		executeJsCommands(webDriver, splitCommands(getJsScript(params)), getJsArguments(webDriver, webLocator, params));
Check that descendants don't return null values, or hadle null correctly

2021-02-15 12:16 UTC, battlemaster approved these changes

2021-02-15 12:25 UTC, Vladimir-Panarin-Exactpro approved these changes

2021-02-15 12:36 UTC, merged