[TH2-1668] Implement support for WebP image encoding
th2-net/remotehand pull request #22
Opened 2021-03-22 10:59 UTC by yarchiksmith

2021-03-22 12:35 UTC, Vladimir-Panarin-Exactpro requested changes

2021-03-22 12:35 UTC, Vladimir-Panarin-Exactpro commented on README.md
> +[Here](https://github.com/th2-net/remotehand/blob/master/www/WebpLibrary.MD) you can see how to use webp library to encoding images.
`... to encode images.`

2021-03-22 12:35 UTC, Vladimir-Panarin-Exactpro commented on build.gradle
> +    compile group: 'net.java.dev.jna', name: 'jna', version: '5.7.0'
Use style as above.

2021-03-22 12:35 UTC, Vladimir-Panarin-Exactpro commented on src/main/java/com/exactprosystems/remotehand/screensaver/ScreenSaver.java
> +public abstract class ScreenSaver<T> {
For me, the name "ScreenSaver" sounds like "screensaver" which is not what is meant here. ScreenshotSaver, maybe? ScreenWriter?

2021-03-22 13:08 UTC, Vladimir-Panarin-Exactpro submitted a review, later dismissed

2021-04-12 15:28 UTC, std000 requested changes

2021-04-12 15:28 UTC, std000 commented on src/main/java/com/exactprosystems/remotehand/screenwriter/WebpScreenWriter.java
> +				result[offset++] = (byte) ((bufferedImage.getRGB(j, i) >> 16) & 0xff);
To many copies of usage `public int getRGB(int x, int y)`
Every one is doing some operations.

2021-04-12 15:28 UTC, std000 commented on src/main/java/com/exactprosystems/remotehand/screenwriter/WebpScreenWriter.java
> +				result[offset++] = (byte) ((bufferedImage.getRGB(j, i) >> 16) & 0xff);
The same as `getRGBAData`

2021-04-12 15:28 UTC, std000 commented on src/main/java/com/exactprosystems/remotehand/screenwriter/WebpScreenWriter.java
> +				result[offset++] = (byte) (bufferedImage.getRGB(j, i) & 0xff);
probably use `java.awt.Color` ?
https://docs.oracle.com/javase/7/docs/api/java/awt/Color.html
Usage:
```
Color (int rgb)
color.getRed()
color.getGreen()
color.getBlue()
color.getAlpha()
```

I suggest it would be simplier to read.

Or Add comments to this method.

2021-04-12 15:28 UTC, std000 commented on src/main/java/com/exactprosystems/remotehand/web/actions/WaitForChanges.java
> +			byte[] currentState = screenWriter.takeElementScreenshot(webDriver, element);
This code should work only with png.
Encoding screenshot to webp can take a long time.
Code is in loop so there are many iterations

2021-04-13 15:19 UTC, std000 commented on src/main/java/com/exactprosystems/remotehand/web/actions/StoreElementState.java
> +		String fileName = screenWriter.takeAndSaveElementScreenshot(screenshotName, webDriver, element);
The same as wait for changes.
This action is used to create initial state on an element

2021-04-15 11:47 UTC, std000 approved these changes

2021-04-15 11:49 UTC, merged